version: '3.8'

services:
  airflow-init:
    image: apache/airflow:2.10.5
    entrypoint: ["airflow", "db", "upgrade"]
    restart: "no"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: airflow-postgres_serials
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  airflow-webserver_serials:
    build: ./airflow
    container_name: airflow-webserver_serials
    restart: always
    depends_on:
      - airflow-init
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=super_secret_key
    privileged: true
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
      - ./parsing/data:/app/data
      - ./model/matrix:/app/matrix
    user: root

  airflow_scheduler_serials:
    user: root
    build: ./airflow
    container_name: airflow-scheduler_serials
    restart: always
    depends_on:
      - airflow-webserver_serials
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__WEBSERVER__SECRET_KEY=super_secret_key
    privileged: true
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow_plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock

  imdb_pars:
    user: root
    build: ./parsing
    volumes:
      - ./parsing/data:/app/data
    restart: 'no'
    command: sleep infinity

  modeling:
    user: root
    build: ./model
    volumes:
      - ./parsing/data:/app/data
      - ./model/matrix:/app/matrix
    restart: 'no'
    depends_on:
      - imdb_pars
    command: sleep infinity

volumes:
  airflow_dags:
  airflow_logs:
  airflow_plugins:
  postgres_data: